module.exports = {
  ...require("./CompilerValue"),
  ...require("./Literal"),
  ...require("./LiteralScalar"),
  ...require("./LiteralCompound"),
  ...require("./Selector"),
  ...require("./Position"),
  ...require("./Rotation"),
  ...require("./Time"),
  ...require("./ResLoc"),
  ...require("./BlockSpec"),
  ...require("./ScoreboardEntry"),
  ...require("./DataPath"),
  ...require("./BossBarProp"),
  ...require("./Operator"),
}